// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://islexetvmnvmsuaubcbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbGV4ZXR2bW52bXN1YXViY2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODYxNjksImV4cCI6MjA2NDE2MjE2OX0.fzNYhr8ke0r__qnoDf-z8cPLo_yNaqK4-bB15lIMvwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);